### ISSUE TITLE
iso-tp/esp32_can  issue

### ISSUE THREAD

**Issue by realfast** [collin80/iso-tp#3]
I am using an esp_32 to try and process large amounts of data. I can run the same sketch on a due with no issues. However, when running this on an esp_32 I get a panic error. 

If I lower the size of the #define MAX_MSGBUF it fails sooner. If I raise this value it goes longer without failing. I am able to upload around 500k bytes of data before this panic happens with the max limit raised. This lets me know that it is overrunning the buffer. 

I have added a bufPTR to the struct in the library which I initialize in my main sketch to the Buffer pointer. I then modified the library to update the Buffer to the bufPTR any time it completes sending a multiframe message or a Single message. This has eliminated the issues I am seeing

**Comment by collin80** [comment]
Unfortunately, that seems really unsurprising. The ESP32 is a cool chip but always seems like nothing but one set of weird problems after another. I can't make a lot of sense out of that part of the crash dump. It should have had a backtrace as well. If you interpret that backtrace it will likely really help to pinpoint the problem.
